
//
//          Copyright Richard Allen Hogaboom 1997 - 2016.
// Distributed under the Boost Software License, Version 1.0.
//    (See accompanying file LICENSE_1_0.txt or copy at
//          http://www.boost.org/LICENSE_1_0.txt)
//
// Boost Software License - Version 1.0 - August 17th, 2003
//
// Permission is hereby granted, free of charge, to any person or organization
// obtaining a copy of the software and accompanying documentation covered by
// this license (the "Software") to use, reproduce, display, distribute,
// execute, and transmit the Software, and to prepare derivative works of the
// Software, and to permit third-parties to whom the Software is furnished to
// do so, all subject to the following:
//
// The copyright notices in the Software and this entire statement, including
// the above license grant, this restriction and the following disclaimer,
// must be included in all copies of the Software, in whole or in part, and
// all derivative works of the Software, unless such copies or derivative
// works are solely in the form of machine-executable object code generated by
// a source language processor.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
// SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
// FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
// ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
// DEALINGS IN THE SOFTWARE.
//

/*
 * NAME
 *
 *     MKRdxPat_perf
 *
 * USAGE
 *
 *     ./MKRdxPat_perf [-c{1-2}] [-s{1-86400}] [-b{1-100000}]
 *
 * ARGUMENTS
 *
 *     None
 *
 * OPTIONS
 *
 *     -c{1-2}      - option 1: repeatedly insert()(fill - monatonic keys)/remove()(empty)
 *                              trie(1 default)
 *                    option 2: fill trie(monatonic keys) then do max_rdx_nodes search()'s
 *                              with random keys
 *
 *     -s{1-86400}  - minimum run time(secs)(30 default)
 *
 *     -b{1-100000} - c option 1: trie will be filled/emptied this many times
 *                    c option 2: the random key set generated on filling the trie will be
 *                                searched for this many times
 *                    (100 default)
 *
 * DESCRIPTION
 *
 *     MKRdxPat_perf is used to evaluate the performance of the MKRdxPat class
 *     (Multi-Key Radix Fast Search) algorithm implementation.  first, change
 *     the three arguments:
 *         const int max_rdx_nodes = 200000;
 *         const int num_keys          = 2;
 *         const int max_key_bytes     = 16;
 *     to match your application.
 *     insert in 'struct app_data{}' your application data node.  Re-compile.  run
 *     ./MKRdxPat_perf [options].  examine the MKRdxPat_perf.results file.
 *     see EXAMPLE OUTPUT below.  the file output includes:
 *         1. the data/time
 *         2. the full cmd line
 *         3. the -c option description
 *         4. the lscpu cmd output - provides some context on the hardware that was
 *                                   used to run the performance test
 *         5. the constructor arguments
 *         6. the trie size
 *         7. the option parameters
 *         8. the incremental number of operations(insert(), remove(), search())
 *            for whatever the -b option is set to
 *         9. the time(secs) the run took and the number of operations performed
 *            in that time
 *         10. the operations per second
 *     subsequent runs will append new data.
 *
 * NOTES
 *
 *     1. you need to select the three constructor arguments based on your application.
 *        remember that max_key_bytes is set to the longest key length.  see the MKRdxPat.hpp
 *        Description section for a detailed explanation of setting key arrays.
 *
 *     2. a more realistic performance evaluation my be had by modifying the code here to
 *        add additional steps always or typically used in your application.  for example,
 *        a call to memset() might be made before an insert()/remove()/search() since in
 *        many cases key arrays are zero filled starting with this.  also, some processing
 *        of node data might be done that is commonly application specific.
 *
 *     3. the default coded constructor arguments in the Description above were selected
 *        based on an application that accessed data nodes by IPv4 and IPv6 addresses - the
 *        two keys.  the longest is the IPv6 address at 16 bytes.  the number of data nodes
 *        was an arbitrary selection.  i've run tests with 2,000,000 data nodes.  if, for
 *        example, the MAC address was added as a third key then the number of keys would
 *        be three but, with the MAC address length at 6 bytes, the IPv6 address would
 *        still be the longest and thus max_key_bytes would still be 16.
 *
 * DEPENDENCIES
 *
 *     MKRdxPat.hpp class
 *
 * BUGS AND LIMITATIONS
 *
 *     No bugs known
 *
 * EXAMPLE OUTPUT
 *
 *     ####################################################################################################
 *     Sat Apr 23 12:41:10 2016
 *
 *     ./MKRdxPat_perf 
 *
 *     PERFORMANCE TEST: Do repeated rdx->insert()(fill trie) / rdx->remove()(empty trie)
 *                       monatonic keys
 *
 *     lscpu:
 *
 *     Architecture:          x86_64
 *     CPU op-mode(s):        32-bit, 64-bit
 *     Byte Order:            Little Endian
 *     CPU(s):                2
 *     On-line CPU(s) list:   0,1
 *     Thread(s) per core:    1
 *     Core(s) per socket:    2
 *     Socket(s):             1
 *     NUMA node(s):          1
 *     Vendor ID:             AuthenticAMD
 *     CPU family:            15
 *     Model:                 107
 *     Model name:            AMD Athlon(tm) 64 X2 Dual Core Processor 4000+
 *     Stepping:              1
 *     CPU MHz:               2109.701
 *     BogoMIPS:              4219.40
 *     Virtualization:        AMD-V
 *     L1d cache:             64K
 *     L1i cache:             64K
 *     L2 cache:              512K
 *     NUMA node0 CPU(s):     0,1
 *     Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat
 *                            pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt
 *                            rdtscp lm 3dnowext 3dnow rep_good nopl pni cx16 lahf_lm cmp_legacy
 *                            svm extapic cr8_legacy 3dnowprefetch lbrv vmmcall
 *
 *     max_rdx_nodes = 1,000,000
 *     num_keys = 3
 *     max_key_bytes = 16
 *         (Modify MKRdxPat_perf.cpp with new parameters and re-compile.)
 *
 *     trie size = 407,000,769b
 *
 *     -c 1 - insert()/remove()(1 default) or search()(2)
 *     -s 30 - minimum run time(sec, 30 default)
 *     -b 100 - block multiplier(100 default)
 *
 *     insert()/remove() increments: 200,000,000(100*2*max_rdx_nodes)
 *
 *     seconds = 739.618731  total inserts/removes = 200,000,000
 *
 *     operations per second = 270,409
 *
 * SEE ALSO
 *
 *     MKRdxPat_test - the MKRdxPat.hpp class test suite
 *
 * AUTHOR
 *
 *     Richard A Hogaboom
 *     richard.hogaboom@gmail.com
 *
 */

#include <iostream>
#include <fstream>
#include <string>
#include <cstring>
#include <ctime>

#include <unistd.h>

#include "MKRdxPat.hpp"

using namespace MultiKeyRdxPat;

using std::cerr;


// take the difference of two timespec structs and return this in a timespec struct
    struct timespec
timespec_diff
    (
        struct timespec start,
        struct timespec end
    )
{
    struct timespec temp;

    if ((end.tv_nsec - start.tv_nsec) < 0) 
    {
        temp.tv_sec = end.tv_sec - start.tv_sec - 1;
        temp.tv_nsec = 1000000000 + end.tv_nsec - start.tv_nsec;
    } 
    else 
    {
        temp.tv_sec = end.tv_sec - start.tv_sec;
        temp.tv_nsec = end.tv_nsec - start.tv_nsec;
    }

    return temp;
}

    int
main
    (
        int argc,
        char **argv
    )
{
    const int TMPSTR_SIZE = 256;
    char tmpstr[TMPSTR_SIZE];

    extern int optind;

    string usage =
        "usage: ./MKRdxPat_perf [-c{1-2}] [-s{1-86400}] [-b{1-100000}]\n"
        "\n"
        "    -c{1-2}      - option 1: repeatedly insert()(fill - monatonic keys)/remove()(empty)\n"
        "                             trie(1 default)\n"
        "                   option 2: fill trie(monatonic keys) then do max_rdx_nodes search()'s\n"
        "                             with random keys\n"
        "\n"
        "    -s{1-86400}  - minimum run time(secs)(30 default)\n"
        "\n"
        "    -b{1-100000} - c option 1: trie will be filled/emptied this many times\n"
        "                   c option 2: the random key set generated on filling the trie will be\n"
        "                               searched for this many times\n"
        "                   (100 default)\n";

    //
    // set these application specific data
    //
    // ================================================

    // MKRdxPat.hpp class constructor arguments
    const int max_rdx_nodes = 1000000;
    const int num_keys      = 3;
    const int max_key_bytes = 16;

    // application data of type app_data defined here
    struct app_data
    {
        int i;
    };

    // ================================================


    // holds sets of keys for max_rdx_nodes sets with num_keys keys of
    // max_key_bytes length with all key booleans set to 1
    // NOTE: the static keyword is needed to ensure that large rdx_key[][][]
    //       arrays do no blow the stack
    static unsigned char rdx_key[max_rdx_nodes][num_keys][1+max_key_bytes];

    app_data *app_datap;

    // enable printf("%'d", n); for commas in large numbers
    setlocale(LC_NUMERIC, "");

    ofstream os;
    os.open("MKRdxPat_perf.results", ofstream::app|ofstream::out);

    // cmd line option defaults
    int pmode_opt = 1;  // performance test case option
    int rtime_opt = 30;  // run time option
    int block_multiply_opt = 100;  // block multiply option

    opterr = 0;
    int opt;
    while ( (opt = getopt(argc, argv, "c:s:b:")) != -1 )
    {
        switch (opt)
        {
            case 'c':
                pmode_opt = atoi(optarg);
                if ( pmode_opt < 1 || pmode_opt > 2 )
                {
                    cerr << usage << "-c option out of range(1 or 2): " << pmode_opt << "\n";
                    exit(1);
                }
                break;

            case 's':
                rtime_opt = atoi(optarg);
                if ( rtime_opt < 1 || rtime_opt > 86400 )
                {
                    cerr << usage << "-s option out of range(1 to 86400): " << rtime_opt << "\n";
                    exit(1);
                }
                break;

            case 'b':
                block_multiply_opt = atoi(optarg);
                if ( block_multiply_opt < 1 || block_multiply_opt > 100000 )
                {
                    cerr << usage << "-b option out of range(1 to 100000): " << block_multiply_opt << "\n";
                    exit(1);
                }
                break;

            case '?':
                cerr << usage << "\n";
                return 1;

            default:
                cerr << "abort(): " << opt << " = getopt(argc, argv, \"c:s:b:\")" << "\n";
                abort();
        }
    }

    if ( optind < argc )
    {
        cerr << usage << "No arguments allowed\n";
        exit(0);
    }

    // set gm time string
    time_t rawtime;
    struct tm * timeinfo;

    time(&rawtime);
    timeinfo = gmtime(&rawtime);
    strftime(tmpstr, TMPSTR_SIZE, "%c", timeinfo);

    os << "####################################################################################################\n"
       << tmpstr << "\n\n";

    for ( int i = 0 ; i < argc ; i++ )
    {
        os << argv[i] << " ";
    }
    os << "\n\n";

    if ( pmode_opt == 1 )
    {
        os << "PERFORMANCE TEST: Do repeated rdx->insert()(fill trie) / rdx->remove()(empty trie)\n"
              "                  monatonic keys\n\nlscpu:\n\n";
    }
    if ( pmode_opt == 2 )
    {
        os << "PERFORMANCE TEST: Do repeated rdx->search()\n"
              "                  monatonic keys/random search\n\nlscpu:\n";
    }

    os.close();

    system("lscpu >> MKRdxPat_perf.results");

    os.open("MKRdxPat_perf.results", ofstream::app|ofstream::out);

    // rdx_key[][][] - generate max_rdx_nodes nodes of num_keys keys of
    // max_key_bytes bytes and set all key booleans to 1
    for ( int n = 0, sum = 0 ; n < max_rdx_nodes ; n++, sum++ )
    {
        for ( int k = 0 ; k < num_keys ; k++ )
        {
            rdx_key[n][k][0] = 1;  // set key boolean to 1
            // keys monatonically increase
            // key is in bytes 1 to max_key_bytes.  sum should be right justified in rdx_key[n][k][<right justified here>].
            memmove(&rdx_key[n][k][max_key_bytes-sizeof(sum)+1], &sum, sizeof(sum));
        }
    }

    // MKRdxPat class trie constructor
    MKRdxPat<app_data> *rdx = new MKRdxPat<app_data>(max_rdx_nodes, num_keys, max_key_bytes);

    os << "\n";
    snprintf(tmpstr, sizeof(tmpstr), "\nmax_rdx_nodes = %'d\nnum_keys = %d\nmax_key_bytes = %d\n",
        max_rdx_nodes, num_keys, max_key_bytes);
    os << tmpstr;
    snprintf(tmpstr, sizeof(tmpstr), "    (Modify MKRdxPat_perf.cpp with new parameters and re-compile.)\n\n");
    os << tmpstr;
    snprintf(tmpstr, sizeof(tmpstr), "trie size = %'db\n\n", rdx->bsize());
    os << tmpstr;

    snprintf(tmpstr, sizeof(tmpstr), "-c %d - insert()/remove()(1 default) or search()(2)\n", pmode_opt);
    os << tmpstr;
    snprintf(tmpstr, sizeof(tmpstr), "-s %d - minimum run time(sec, 30 default)\n", rtime_opt);
    os << tmpstr;
    snprintf(tmpstr, sizeof(tmpstr), "-b %d - block multiplier(100 default)\n\n", block_multiply_opt);
    os << tmpstr;

    switch ( pmode_opt )
    {
        case 1:
            {
                long total_inserts_removes = 0;
                struct timespec tstart={0,0}, tend={0,0}, tdiff={0,0};
                double sec;
                int return_code;

                snprintf(tmpstr, sizeof(tmpstr), "insert()/remove() increments: %'d(%d*2*max_rdx_nodes)\n\n",
                    block_multiply_opt*2*max_rdx_nodes, block_multiply_opt);
                os << tmpstr;

                clock_gettime(CLOCK_MONOTONIC, &tstart);

                for (;;)
                {
                    for ( int i = 0 ; i < block_multiply_opt ; i++ )
                    {
                        for ( int n = 0 ; n < max_rdx_nodes ; n++ )
                        {
                            return_code = rdx->insert((unsigned char *)rdx_key[n], &app_datap);

                            if ( return_code != 0 )
                            {
                                os << "insert(): data node = " << n << " return_code = " << return_code << "\n";
                            }
                        }

                        for ( int n = 0 ; n < max_rdx_nodes ; n++ )
                        {
                            app_datap = rdx->remove((unsigned char *)rdx_key[n]);

                            if ( app_datap == NULL )
                            {
                                os << "remove(): data node = " << n << " return = NULL" << "\n";
                            }
                        }
                    }

                    total_inserts_removes += max_rdx_nodes*2*block_multiply_opt;

                    clock_gettime(CLOCK_MONOTONIC, &tend);

                    tdiff = timespec_diff(tstart, tend);
                    sec = tdiff.tv_sec + tdiff.tv_nsec/1E9;

                    if ( sec > rtime_opt )
                    {
                        break;
                    }
                }

                snprintf(tmpstr, sizeof(tmpstr), "seconds = %f  total inserts/removes = %'ld\n\n", sec, total_inserts_removes);
                os << tmpstr;

                long ops_per_sec;
                ops_per_sec = total_inserts_removes/sec;
                snprintf(tmpstr, sizeof(tmpstr), "operations per second = %'ld\n\n", ops_per_sec);
                os << tmpstr;
            }
            break;

        case 2:
            {
                long total_searches = 0;
                int random[max_rdx_nodes];  // for random key search()
                struct timespec tstart={0,0}, tend={0,0}, tdiff={0,0};
                double sec;

                snprintf(tmpstr, sizeof(tmpstr), "search() increments: %'d(%d*max_rdx_nodes)\n\n",
                    block_multiply_opt*max_rdx_nodes, block_multiply_opt);
                os << tmpstr;

                srand(time(NULL));
                for ( int n = 0 ; n < max_rdx_nodes ; n++ )
                {
                    rdx->insert((unsigned char *)rdx_key[n], &app_datap);
                    random[n] = rand() % max_rdx_nodes;  // not crypto random - will produce some duplicates - ok
                }

                clock_gettime(CLOCK_MONOTONIC, &tstart);

                for (;;)
                {
                    for ( int i = 0 ; i < block_multiply_opt ; i++ )
                    {
                        for ( int n = 0 ; n < max_rdx_nodes ; n++ )
                        {
                            app_datap = rdx->search((unsigned char *)rdx_key[random[n]]);

                            if ( app_datap == NULL )
                            {
                                os << "search(): data node = " << n << " return = NULL" << "\n";
                            }

                            total_searches++;
                        }
                    }

                    clock_gettime(CLOCK_MONOTONIC, &tend);

                    tdiff = timespec_diff(tstart, tend);
                    sec = tdiff.tv_sec + tdiff.tv_nsec/1E9;

                    if ( sec > rtime_opt )
                    {
                        break;
                    }
                }

                snprintf(tmpstr, sizeof(tmpstr), "seconds = %f  total searches = %'ld\n\n", sec, total_searches);
                os << tmpstr;

                long ops_per_sec;
                ops_per_sec = total_searches/sec;
                snprintf(tmpstr, sizeof(tmpstr), "operations per second = %'ld\n\n", ops_per_sec);
                os << tmpstr;
            }
            break;

        default:
            {
                os << "Bad -c option.\n";
            }
            break;
    }
}

